In [22]:
import pandas as pd
import numpy as np


In [23]:
split_data = pd.read_csv("split_data_with_sentiments.csv")
X_bow = pd.read_csv("X_bow.csv")
X_tfidf = pd.read_csv("X_tfidf.csv")
X_dict = pd.read_csv("X_dict.csv")

In [24]:
print(X_tfidf.shape)

(4992, 9549)


In [25]:
y = split_data['ttype']

1 Разделить текстовый корпус Рубцовой на обучающий и тестовый наборы

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y,test_size=0.3, random_state=42)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3494, 9549) (3494,)
(1498, 9549) (1498,)


2 Используя текстовые вектора из лр2, построить линейную регрессию, регрессию со штрафом (L1, L2 и L1+L2) и полиномиальную регрессию

Построить линейную регрессию

In [27]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(X_train, y_train)
linear.coef_

array([-9.76380317e+11,  3.98380765e+12,  1.31966874e+12, ...,
        0.00000000e+00,  0.00000000e+00,  2.19379385e+12])

Построить регрессию со штрафом L1

In [28]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)
lasso.coef_

array([0., 0., 0., ..., 0., 0., 0.])

Построить регрессию со штрафом L2

In [29]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)
ridge.coef_

array([0.23230708, 0.23880033, 0.0424824 , ..., 0.        , 0.        ,
       0.06763839])

Построить регрессию со штрафом L1+L2

In [30]:
from sklearn.linear_model import ElasticNet
elastic = ElasticNet(random_state=0)
elastic.fit(X_train, y_train)
elastic.coef_

array([0., 0., 0., ..., 0., 0., 0.])

3 Вычислить точность работы моделей (MSE, R2) и сравнить результаты

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

Линейная регрессия

In [31]:
linear_predictions = linear.predict(X_test)
print(mean_squared_error(y_test, linear_predictions))
print(r2_score(y_test, linear_predictions))

3.624718007926536e+24
-3.6275696217439607e+24


Регрессия со штрафом L1

In [32]:
lasso_predictions = lasso.predict(X_test)
print(mean_squared_error(y_test, lasso_predictions))
print(r2_score(y_test, lasso_predictions))

1.0003154196306112
-0.0011023810621386687


Регрессия со штрафом L2

In [33]:
ridge_predictions = ridge.predict(X_test)
print(mean_squared_error(y_test, ridge_predictions))
print(r2_score(y_test, ridge_predictions))

0.8907432646870278
0.10855597575159248


Регрессия со штрафом L1+L2

In [34]:
elastic_predictions = elastic.predict(X_test)
print(mean_squared_error(y_test, elastic_predictions))
print(r2_score(y_test, elastic_predictions))

1.0003154196306112
-0.0011023810621386687


Построить полиномиальную регрессию

In [35]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=1)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)
linear.fit(X_train_poly,y_train)
linear.coef_

array([ 3.08156470e+11, -1.02782376e+12,  7.99332524e+11, ...,
        0.00000000e+00,  0.00000000e+00,  1.71379597e+12])

In [36]:
poly_predictions = linear.predict(X_test_poly)
print(mean_squared_error(y_test, poly_predictions))
print(r2_score(y_test, poly_predictions))

8.033397518692925e+24
-8.039717499258331e+24


4 Уменьшить размерность признаков и проделать пункт 2 и 3

In [37]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
X_tfidf = pca.fit_transform(X_tfidf)
print(X_tfidf.shape)

(4992, 5)


In [38]:
X_train_, X_test_, y_train_, y_test_ = train_test_split(X_tfidf, y, test_size=0.3, random_state=42)
print(X_train.shape)
print(X_test.shape)

(3494, 9549)
(1498, 9549)


In [39]:
linear.fit(X_train_, y_train_)
linear_pred = linear.predict(X_test_)
print(mean_squared_error(y_test_, linear_pred))
print(r2_score(y_test_, linear_pred))

0.9917594690184746
0.007460300630025007


In [40]:
lasso.fit(X_train_, y_train_)
lasso_pred = lasso.predict(X_test_)
print(mean_squared_error(y_test_, lasso_pred))
print(r2_score(y_test_, lasso_pred))

1.0003154196306112
-0.0011023810621386687


In [41]:
ridge.fit(X_train_, y_train_)
ridge_pred = ridge.predict(X_test_)
print(mean_squared_error(y_test_, ridge_pred))
print(r2_score(y_test_, ridge_pred))

0.9907009056883177
0.00851969674601838


In [42]:
elastic.fit(X_train_, y_train_)
elastic_pred = elastic.predict(X_test_)
print(mean_squared_error(y_test_, elastic_pred))
print(r2_score(y_test_, elastic_pred))

1.0003154196306112
-0.0011023810621386687


In [43]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_train_poly_ = poly.fit_transform(X_train_)
X_test_poly_ = poly.fit_transform(X_test_)
linear.fit(X_train_poly_,y_train_)
linear_pred = linear.predict(X_test_poly_)
print(mean_squared_error(y_test_, linear_pred))
print(r2_score(y_test_, linear_pred))

0.9943468512759541
0.004870882844545621
